name: "Cache NixOS configurations"
on:
  workflow_dispatch:

jobs:
  oracleamd2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: propheci
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build .#nixosConfigurations.oracleamd2.config.system.build.toplevel --accept-flake-config -L
